knp_snappy:
    pdf:
        enabled:    true
        #binary:    /usr/local/bin/wkhtmltopdf
        binary:     '\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"'
        options:    []
    image:
        enabled:    true
        binary:     '\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"'
        options:    []