twig:
    default_path: '%kernel.project_dir%/templates'# config/packages/twig.yaml
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        pathToWeb: "%kernel.project_dir%\\public"

when@test:
    twig:
        strict_variables: true
